# Generated by Django 5.1.1 on 2025-04-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_appointment_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
