# Generated by Django 5.1.1 on 2025-04-17 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
