# Generated by Django 5.1.1 on 2025-04-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegister',
            fields=[
                ('doctor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctors_speciality', models.CharField(max_length=80)),
                ('doctor_password', models.CharField(max_length=100)),
                ('doctor_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=100)),
                ('staff_password', models.CharField(max_length=100)),
                ('staff_phone', models.CharField(max_length=20)),
                ('staff_address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StaffRegister',
        ),
    ]
