# Generated by Django 5.1.1 on 2025-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_doctorregister_staffrequest_delete_staffregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=20)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctors_speciality', models.CharField(max_length=80)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('doctor_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorRegister',
        ),
    ]
