# Generated by Django 5.1.1 on 2025-04-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_doctorrequest_delete_doctorregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegister',
            fields=[
                ('doctor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctors_speciality', models.CharField(max_length=80)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('doctor_phone', models.CharField(max_length=20)),
                ('doctor_password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
