# Generated by Django 5.1.1 on 2025-04-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_doctorregister'),
        ('mainapp', '0004_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorRegister',
        ),
    ]
