# Generated by Django 5.1.1 on 2025-04-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_doctorregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorRegister',
        ),
    ]
