# Generated by Django 5.1.1 on 2025-04-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_doctorregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_email', models.EmailField(max_length=254)),
                ('staff_password', models.CharField(max_length=100)),
                ('staff_phone', models.CharField(max_length=20)),
                ('staff_address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
