# Generated by Django 5.1.1 on 2025-04-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
